version: '3.7'

services:
  poc-gql-apollosrv:
    build: .
    image: graphql-apollosrv:poc
    container_name: poc-gql-apollosrv
    ports:
      - "8008:8008"
    restart: always
    volumes:
      - "./src:/app/src"
      - "./data:/app/data"
    networks:
      - poc-graphql

networks:
  poc-graphql:
    name: poc-graphql
    external: true
